org: binhrobles
service:
  name: ghosts-api
  org: binhrobles

custom:
  webpack:
    includeModules: true
    packager: 'yarn'
    webpackConfig: ./webpack.config.js

  customDomain:
    domainName: ghosts-api.binhrobles.com
    basePath: ${opt:stage, self:provider.stage}
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'

  serverless-offline:
    httpPort: 4000
    useChildProcesses: true

plugins:
  - serverless-webpack
  - serverless-localstack
  - serverless-offline

provider:
  name: aws
  region: us-west-1
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  individually: true

functions:
  - ${file(./functions/entries/definition.yml)}

resources:
  - ${file(./resources/iam-roles.yml)}
  - ${file(./resources/dynamo.yml)}
