org: binhrobles
service: ghosts-api

custom:
  stage: ${opt:stage, self:provider.stage}

  # Configures throttling settings for all http endpoints
  apiGatewayThrottling:
    maxRequestsPerSecond: 5
    maxConcurrentRequests: 5

  webpack:
    includeModules: true
    packager: 'yarn'
    webpackConfig: ./webpack.config.js

plugins:
  - serverless-webpack
  - serverless-api-gateway-throttling

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  logs:
    restApi:
      level: ERROR
      fullExecutionData: false
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    STAGE: ${self:custom.stage}

package:
  individually: true

functions:
  - ${file(./src/entries/definition.yml)}

resources:
  - ${file(./resources/iam-roles.yml)}
