org: binhrobles
service:
  name: ghosts-api
  org: binhrobles

custom:
  stage: ${opt:stage, self:provider.stage}

  domains:
    prod: ghosts-api.binhrobles.com
    other: personal.ghosts-api.binhrobles.com

  webpack:
    includeModules: true
    packager: 'yarn'
    webpackConfig: ./webpack.config.js

  customDomain:
    stage: ${self:custom.stage}
    domainName: ${self:custom.domains.${self:custom.stage}, self:custom.domains.other}
    basePath: ""
    createRoute53Record: false
    endpointType: 'regional'

  serverless-offline:
    httpPort: 4000
    useChildProcesses: true

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  individually: true

functions:
  - ${file(./src/entries/definition.yml)}
  - ${file(./src/indexer/definition.yml)}
  - ${file(./src/query/definition.yml)}
  - ${file(./src/provision/definition.yml)}

resources:
  - ${file(./resources/iam-roles.yml)}
