---
Resources:
  EntriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema: 
        - AttributeName: "_id"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "_id"
          AttributeType: "S"
      ProvisionedThroughput: 
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"
      TimeToLiveSpecification:
        AttributeName: "TTL"
        Enabled: True
